project:
    type: book
    output-dir: _book

book:
<<<<<<< HEAD
  title: "Bitácora de Estadística Multivariada con R"
=======
  title: "Estadística Multivariada con R"
>>>>>>> 49b567e7dbc9c962aa048237613ad5af8870e5a5
  author: "Samuel Solís Barrón"
  date: "5/26/2026"
  chapters:
    - index.qmd
    - matrix-algebra/matrix-algebra.qmd
    - data-frame/data-frame.qmd
    - data-visualization/data-visualization.qmd
    - manova/manova.qmd
    - pca/pca.qmd
    - pcoa/pcoa.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true
    css: styles.css

editor: source