project:
    type: book
    output-dir: _book

book:
  title: "Bitácora de Estadística Multivariada con R"
  author: "Samuel Solís Barrón"
  date: "5/26/2026"
  chapters:
    - index.qmd
    - matrix-algebra/matrix-algebra.qmd
    - data-frame/data-frame.qmd
    - data-visualization/data-visualization.qmd
    - manova/manova.qmd
    - pca/pca.qmd
    - pcoa/pcoa.qmd
    - multivariate-hypotheses/multivariate-hypotheses.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true
    css: styles.css

editor: source